In [ ]:
import pandas as pd

In [ ]:
pip install transformers accelerate torch torchvision pillow

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.25.0+cu128)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (11.3.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.6.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [ ]:
from transformers import AutoProcessor, AutoModelForImageTextToText
import torch
import torch.nn.functional as F

In [ ]:
df_questions = pd.read_csv("df_questions_2 (1).csv")

In [ ]:
df_questions.head()

,tag,image_name,image_data_url,true_description,description_for_answer,description_for_question,false_source_image_name,generated_question,used_prompt
0,concurrence,882048099.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman in a blue bathing suit and straw hat ...,A woman in a blue bathing suit and straw hat ...,A woman in a blue bathing suit and straw hat ...,NaN,Is there a woman in a blue bathing suit and st...,You need to formulate a single binary (yes/no)...
1,false_detail,882048099.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman in a blue bathing suit and straw hat ...,A woman in a gray bathing suit and straw hat ...,A woman in a gray bathing suit and straw hat ...,882048099.jpg,What color is the bathing suit the woman is we...,You are given two descriptions of the same ima...
2,image,882048099.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman in a blue bathing suit and straw hat ...,Four women in all black barefoot posing on th...,A woman in a blue bathing suit and straw hat ...,5922945248.jpg,Is there a woman in a blue bathing suit and st...,You need to formulate a single binary (yes/no)...
3,text,882048099.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman in a blue bathing suit and straw hat ...,Four women in all black barefoot posing on th...,Four women in all black barefoot posing on th...,5922945248.jpg,Are there women posing on the beach?,You need to formulate a single binary (yes/no)...
4,concurrence,199413509.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman peers out from her halfway opened blu...,A woman peers out from her halfway opened blu...,A woman peers out from her halfway opened blu...,NaN,Is there a woman peeking out from a blue door?,You need to formulate a single binary (yes/no)...

In [ ]:
db_fd = df_questions[df_questions["tag"] == "false_detail"]

In [ ]:
db_con = df_questions[df_questions["tag"] == "concurrence"]

In [ ]:
db_i = df_questions[df_questions["tag"] == "image"]

In [ ]:
db_t = df_questions[df_questions["tag"] == "text"]

Запускаем модель локально. Для всех сценариев использовали Qwen3-VL-2B-Instruct, а также дополнительно для false_detail использовали ещё одну модель Qwen3-VL-4B-Instruct, чтобы посмотреть улучшатся ли результаты ответов модели с большим количеством параметров.

In [ ]:
processor = AutoProcessor.from_pretrained("Qwen/Qwen3-VL-2B-Instruct")
HF_TOKEN = ""

processor = AutoProcessor.from_pretrained(
    "Qwen/Qwen3-VL-2B-Instruct",
    token=HF_TOKEN
)

model = AutoModelForImageTextToText.from_pretrained(
    "Qwen/Qwen3-VL-2B-Instruct",
    token=HF_TOKEN,
    torch_dtype=torch.bfloat16,   # экономия памяти GPU
    device_map="cuda"             # cuda - явно на GPU; auto если несколько GPU или нет уверенности
)
model.eval()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

chat_template.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/4.26G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/625 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/269 [00:00<?, ?B/s]

Qwen3VLForConditionalGeneration(
  (model): Qwen3VLModel(
    (visual): Qwen3VLVisionModel(
      (patch_embed): Qwen3VLVisionPatchEmbed(
        (proj): Conv3d(3, 1024, kernel_size=(2, 16, 16), stride=(2, 16, 16))
      )
      (pos_embed): Embedding(2304, 1024)
      (rotary_pos_emb): Qwen3VLVisionRotaryEmbedding()
      (blocks): ModuleList(
        (0-23): 24 x Qwen3VLVisionBlock(
          (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
          (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
          (attn): Qwen3VLVisionAttention(
            (qkv): Linear(in_features=1024, out_features=3072, bias=True)
            (proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (mlp): Qwen3VLVisionMLP(
            (linear_fc1): Linear(in_features=1024, out_features=4096, bias=True)
            (linear_fc2): Linear(in_features=4096, out_features=1024, bias=True)
            (act_fn): GELUTanh()
          )
        )
      )
      (merger): Qwen3VLVisionPatchMerger(
        (norm): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
        (linear_fc1): Linear(in_features=4096, out_features=4096, bias=True)
        (act_fn): GELU(approximate='none')
        (linear_fc2): Linear(in_features=4096, out_features=2048, bias=True)
      )
      (deepstack_merger_list): ModuleList(
        (0-2): 3 x Qwen3VLVisionPatchMerger(
          (norm): LayerNorm((4096,), eps=1e-06, elementwise_affine=True)
          (linear_fc1): Linear(in_features=4096, out_features=4096, bias=True)
          (act_fn): GELU(approximate='none')
          (linear_fc2): Linear(in_features=4096, out_features=2048, bias=True)
        )
      )
    )
    (language_model): Qwen3VLTextModel(
      (embed_tokens): Embedding(151936, 2048)
      (layers): ModuleList(
        (0-27): 28 x Qwen3VLTextDecoderLayer(
          (self_attn): Qwen3VLTextAttention(
            (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
            (k_proj): Linear(in_features=2048, out_features=1024, bias=False)
            (v_proj): Linear(in_features=2048, out_features=1024, bias=False)
            (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
            (q_norm): Qwen3VLTextRMSNorm((128,), eps=1e-06)
            (k_norm): Qwen3VLTextRMSNorm((128,), eps=1e-06)
          )
          (mlp): Qwen3VLTextMLP(
            (gate_proj): Linear(in_features=2048, out_features=6144, bias=False)
            (up_proj): Linear(in_features=2048, out_features=6144, bias=False)
            (down_proj): Linear(in_features=6144, out_features=2048, bias=False)
            (act_fn): SiLUActivation()
          )
          (input_layernorm): Qwen3VLTextRMSNorm((2048,), eps=1e-06)
          (post_attention_layernorm): Qwen3VLTextRMSNorm((2048,), eps=1e-06)
        )
      )
      (norm): Qwen3VLTextRMSNorm((2048,), eps=1e-06)
      (rotary_emb): Qwen3VLTextRotaryEmbedding()
    )
  )
  (lm_head): Linear(in_features=2048, out_features=151936, bias=False)
)

In [ ]:
from tqdm import tqdm

In [ ]:
def process_data(df, question_type, output_file):

  if "model_output" not in df.columns:
    df["model_output"] = None
  if "output_probs" not in df.columns:
    df["output_probs"] = None

  for i in tqdm(df.index):
    if question_type == "binary":
      message = {"role": "user",
          "content": [
              {"type": "image", "url": df.at[i, "image_data_url"]},
              {"type": "text",
                "text": f"""In the picture {df.at[i, "description_for_answer"]}.
                Question 1: {df.at[i, "generated_question"]}.
                Answer with one word YES or NO.
                Question 2: How confident are you in this answer?
                Answer with one number 0-100, where 0 is “Absolutely not confident” and 100 is “Absolutely confident”.
                Return your answer in python list format[Question 1 answer, Question 2 answer]
                """}
          ]}
    elif question_type == "detail":
      message = {"role": "user",
         "content": [
             {"type": "image", "url": df.at[i, "image_data_url"]},
             {"type": "text",
              "text": f"""In the picture {df.at[i, "description_for_answer"]}.
              Question 1: {df.at[i, "generated_question"]}.
              Answer with one word.
              Question 2: How confident are you in this answer?
              Answer with one number 0-100, where 0 is “Absolutely not confident” and 100 is “Absolutely confident”.
              Return your answer in python list format[Question 1 answer, Question 2 answer]
              """}
         ]}

    inputs = processor.apply_chat_template(
      [message],
      add_generation_prompt=True,
      tokenize=True,
      return_dict=True,
      return_tensors="pt",
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=40,
            return_dict_in_generate=True,  # возвращает объект с полями, не просто тензор
            output_scores=True,            # логиты на каждом шаге (после penalties)
        )

    # Декодирование ответа
    prompt_len = inputs["input_ids"].shape[-1]
    generated_ids = outputs.sequences[:, prompt_len:]
    output = processor.decode(generated_ids[0], skip_special_tokens=True)
    df.at[i, "model_output"] = output

    # Извлечение логитов / вероятностей
    probs_list = []
    for step, score in enumerate(outputs.scores):
        # score: [batch_size, vocab_size]
        probs = F.softmax(score[0].float(), dim=-1)
        top_probs, top_ids = probs.topk(5)
        #top_tokens = processor.tokenizer.convert_ids_to_tokens(top_ids.tolist())
        top_tokens = [
            processor.tokenizer.decode([tid], skip_special_tokens=False)
            for tid in top_ids.tolist()
        ]
        pairs = [(tok, f"{p:.6f}") for tok, p in zip(top_tokens, top_probs.tolist())]
        probs_list.append(pairs)

    df.at[i, "output_probs"] = probs_list

  df.to_csv(output_file, index=False)
  return df

In [ ]:
res = process_data(db_fd, "detail", "false_detail_results.csv")

/tmp/ipykernel_1240/774376844.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["model_output"] = None
/tmp/ipykernel_1240/774376844.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["output_probs"] = None
100%|██████████| 300/300 [39:20<00:00,  7.87s/it]

In [ ]:
res = process_data(db_con, "binary", "concurrence_results.csv")

/tmp/ipykernel_1240/774376844.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["model_output"] = None
/tmp/ipykernel_1240/774376844.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["output_probs"] = None
100%|██████████| 300/300 [40:08<00:00,  8.03s/it]

In [ ]:
res = process_data(db_i, "binary", "image_results.csv")

/tmp/ipykernel_1240/774376844.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["model_output"] = None
/tmp/ipykernel_1240/774376844.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["output_probs"] = None
100%|██████████| 300/300 [40:21<00:00,  8.07s/it]

In [ ]:
res = process_data(db_t, "binary", "text_results.csv")

In [ ]:
res

,tag,image_name,image_data_url,true_description,description_for_answer,description_for_question,false_source_image_name,generated_question,used_prompt,model_output,output_probs
2,image,882048099.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman in a blue bathing suit and straw hat ...,Four women in all black barefoot posing on th...,A woman in a blue bathing suit and straw hat ...,5922945248.jpg,Is there a woman in a blue bathing suit and st...,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
6,image,199413509.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman peers out from her halfway opened blu...,A man in a blue shirt smiles at a baby he 's ...,A woman peers out from her halfway opened blu...,787907341.jpg,Is there a woman peeking out from a blue door?,You need to formulate a single binary (yes/no)...,"[NO, 75]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
10,image,2825540754.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",a little boy is running on the beach with a r...,A young man dressed in black dress clothes li...,a little boy is running on the beach with a r...,3823691082.jpg,Is there a little boy running on the beach wit...,You need to formulate a single binary (yes/no)...,"[NO, 100]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
14,image,4850944716.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",an older man wearing a suit has his arms fold...,The little girl wearing a pink hat is bending...,an older man wearing a suit has his arms fold...,537579448.jpg,Is there an older man in a suit looking into a...,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
18,image,4526883901.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...","A white-haired man with glasses , wearing a g...",A woman in a brown UPS uniform is handling pa...,"A white-haired man with glasses , wearing a g...",3384702365.jpg,Is there a man working on a sculpture?,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
22,image,523249012.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",The man in the white shirt is sitting on a ro...,a little boy is running on the beach with a r...,The man in the white shirt is sitting on a ro...,2825540754.jpg,Is there a man sitting on a rock with a pole i...,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
26,image,3183330562.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A group of kids in summer play clothes follow...,A blond woman in heels and a semi revealing d...,A group of kids in summer play clothes follow...,4541453490.jpg,Are there kids following a young man?,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
30,image,4812170955.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A small child in a blue outfit is looking off...,Two soldiers at an event center are watching ...,A small child in a blue outfit is looking off...,5450688421.jpg,Is there a child in a blue outfit looking at t...,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
34,image,523327429.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A man holding up a red sign that offers the h...,A golden retriever jumps off of a blue surfbo...,A man holding up a red sign that offers the h...,3648160673.jpg,Is there a man holding up a red sign?,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
38,image,2425148763.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman in a red shirt is speaking at a table...,A man with red-hair dressed in a reflective j...,A woman in a red shirt is speaking at a table...,3495815292.jpg,Is there a woman speaking at a table?,You need to formulate a single binary (yes/no)...,"[NO, 75]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
42,image,2969380952.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A few men sprint across the grass in competit...,A man in a white shirt lays cement on a brick...,A few men sprint across the grass in competit...,113637264.jpg,Are there men sprinting across the grass?,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
46,image,3384702365.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman in a brown UPS uniform is handling pa...,The woman in the red jacket looks as if she w...,A woman in a brown UPS uniform is handling pa...,393987665.jpg,Is there a woman in a UPS uniform handling pac...,You need to formulate a single binary (yes/no)...,"[NO, 70]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
50,image,3470711198.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A man with a white shirt holds a water bottle...,A rock singer in a pink shirt and jeans with ...,A man with a white shirt holds a water bottle...,283146608.jpg,Is there a man holding a water bottle in the p...,You need to formulate a single binary (yes/no)...,"[NO, 100]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
54,image,7306334328.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A man wearing a red garment is hunched over a...,Five people are in a swimming pool 3 ft . dee...,A man wearing a red garment is hunched over a...,2788489062.jpg,Is a man wearing a red garment hunched over an...,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
58,image,508838116.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman in a green striped shirt is standing ...,A young man in white t-shirt is sitting on th...,A woman in a green striped shirt is standing ...,4799652268.jpg,Is there a woman in a green striped shirt in t...,You need to formulate a single binary (yes/no)...,"[NO, 100]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
62,image,4764008740.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",An older woman in an off-white blouse is sitt...,A woman and a dog both kneel with their heads...,An older woman in an off-white blouse is sitt...,2467850190.jpg,Is there an older woman sitting on a stone she...,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
66,image,1801063894.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A woman in a yellow bathing suit gets ready t...,Five young blond and light brown-haired girls...,A woman in a yellow bathing suit gets ready t...,3152291140.jpg,Is there a woman in a yellow bathing suit prep...,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
70,image,503090187.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...","A man with a digital camera , looking at the ...",A little girl with a hat sits between a woman...,"A man with a digital camera , looking at the ...",3730011701.jpg,Is the man looking at the screen of the digita...,You need to formulate a single binary (yes/no)...,"[NO, 100]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
74,image,2766765386.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...",A surfer in a black wetsuit surfs on a medium...,A woman wearing bike shorts and a skirt is ri...,A surfer in a black wetsuit surfs on a medium...,2004326408.jpg,Is there a surfer in a black wetsuit surfing o...,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."
78,image,6204719881.jpg,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAtAC...","In the foreground , a soccer player wearing o...",A blue Harley motorcycle is one of a group of...,"In the foreground , a soccer player wearing o...",4652450030.jpg,Is there a soccer player in the foreground?,You need to formulate a single binary (yes/no)...,"[NO, 0]","[[([, 1.000000), (#, 0.000000), (!, 0.000000),..."

Запускаем модель через api (для false_detail), так как локально запустить модель qwen3-vl-8b-instruct не получилось из-за ограничений на gpu.

In [ ]:
import asyncio
from tqdm import tqdm
from openai import AsyncOpenAI

OPENROUTER_API_KEY = ""
MODEL = "qwen/qwen3-vl-8b-instruct"


async def process_df_async_detail(
    df,
    concurrency=8,
    save_every=5,
    save_path=None,
):
    df = df.copy()

    if "model_output" not in df.columns:
        df["model_output"] = None
    if "used_prompt" not in df.columns:
        df["used_prompt"] = None

    client = AsyncOpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=OPENROUTER_API_KEY,
    )

    sem = asyncio.Semaphore(concurrency)

    async def process_one(index):
        async with sem:
            row = df.loc[index]

            content = [
                {
                    "type": "image_url",
                    "image_url": {"url": row["image_data_url"]},
                },
                {
                    "type": "text",
                    "text": f"""In the picture {row['description_for_answer']}.
                    Question 1: {row['generated_question']}.
                    Answer with one word.
                    Question 2: How confident are you in this answer?
                    Answer with one number 0-100, where 0 is "Absolutely not confident" and 100 is "Absolutely confident".
                    Return your answer in python list format [Question 1 answer, Question 2 answer].
                    """,
                },
            ]

            try:
                completion = await client.chat.completions.create(
                    model=MODEL,
                    messages=[
                        {
                            "role": "user",
                            "content": content,
                        }
                    ],
                )

                text = completion.choices[0].message.content.strip()
                used_prompt = content[1]["text"]
                return index, text, used_prompt

            except Exception as e:
                print(f"Ошибка в строке {index}: {e}")
                used_prompt = content[1]["text"]
                return index, None, used_prompt

    tasks = [process_one(i) for i in df.index]
    done_count = 0

    for fut in tqdm(asyncio.as_completed(tasks), total=len(tasks)):
        index, output, used_prompt = await fut

        df.at[index, "model_output"] = output
        df.at[index, "used_prompt"] = used_prompt
        done_count += 1

        if save_path and done_count % save_every == 0:
            df.to_csv(save_path, index=False)

    if save_path:
        df_to_save = df.drop(columns=["image_data_url"], errors="ignore")
        df_to_save.to_csv(save_path, index=False)

    return df

In [ ]:
df_questions = pd.read_csv("df_questions_new.csv")

db_fd = df_questions[df_questions["tag"] == "false_detail"]
result = await process_df_async_detail(
    db_fd,
    concurrency=8,
    save_path="fd_results_8b_api.csv"
)